version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: coinwash-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: coinwash
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - coinwash_mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00
    networks:
      - coinwash-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-p${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # Redis 캐시
  redis:
    image: redis:7.0-alpine
    container_name: coinwash-redis
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
      - coinwash_redis_data:/data
    networks:
      - coinwash-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      timeout: 20s
      retries: 5
      interval: 10s
      start_period: 10s

  # Spring Boot 애플리케이션
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinwash-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - coinwash-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 20s
      retries: 5
      interval: 30s
      start_period: 60s

# 볼륨 정의
volumes:
  coinwash_mysql_data:
    driver: local
  coinwash_redis_data:
    driver: local

# 네트워크 정의
networks:
  coinwash-network:
    driver: bridge